<?php
$title = $this->translate('Add a new task');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title);?></h1>

<?php 
$form = $this->form;
if($id = $form->get('id')->getValue()) {
	$form->setAttribute('action', $this->url('task', array('action' => 'edit', 'id' => $id)));
} else {
	$form->setAttribute('action', $this->url('task', array('action' => 'add')));
}
//$form->get('submit')->setAttributes(array('value' => 'Add'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
$title_ele = $form->get('title');
echo $this->formRow($title_ele);
//echo $this->formRow($form->get('completed'));

?>

<div>
<?php 
echo $this->formInput($form->get('submit'));
?>
</div>
<?php 
echo $this->form()->closeTag($form);
?>