<?php
 $title = $this->translate('My task list');
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p><a href="<?php echo $this->url('task', array(
         'action'=>'add'));?>"><?php echo $this->translate('Add new item');?></a></p>

 <table class="table">
 <tr>
     <th><?php echo $this->translate('Task')?></th>
     <th><?php echo $this->translate('Created')?></th>
     <th><?php echo $this->translate('Completed?')?></th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($tasks as $task):?>
 <tr>
 	<td><?php echo $this->escapeHtml($task->getTitle());?></td>
 	<td><?php echo $task->getCreated();?></td>
 	<td><?php echo $task->getCompleted() ? $this->translate('yes') : $this->translate('no');?></td>
 	<td>
 		<a href="<?php echo $this->url('task', array('action'=>'edit', 'id'=>$task->getId()));?>"><?php echo $this->translate('edit');?></a>
 		<a href="<?php echo $this->url('task', array('action'=>'delete', 'id'=>$task->getId()));?>"><?php echo $this->translate('delete');?></a>
 	</td>
 </tr>
 <?php endforeach;?>
 </table>